-- Up Migration
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_categories_updated_at
    BEFORE UPDATE ON categories
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Add indexes
CREATE INDEX idx_categories_name ON categories(name);
CREATE INDEX idx_categories_is_active ON categories(is_active);
CREATE INDEX idx_categories_sort_order ON categories(sort_order);

-- Add some default categories
INSERT INTO categories (name, description, sort_order) VALUES
('Ana Yemekler', 'Restoranımızın özel ana yemekleri', 1),
('Çorbalar', 'Günlük hazırlanan taze çorbalar', 2),
('Salatalar', 'Taze ve sağlıklı salatalar', 3),
('İçecekler', 'Sıcak ve soğuk içecekler', 4),
('Tatlılar', 'Özel ev yapımı tatlılar', 5);

-- Down Migration
-- To rollback, uncomment and run these commands:
/*
DROP TRIGGER IF EXISTS update_categories_updated_at ON categories;
DROP FUNCTION IF EXISTS update_updated_at_column();
DROP TABLE IF EXISTS categories;
*/ 